import type { Metadata } from "next";

import "./globals.css";

import { ThemeProvider } from "@/app/Contexts/ThemeProvider";
import { DetailViewProvider } from "./Contexts/DetailViewContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="pink"
          themes={["pink", "yellow", "blue"]}
        >
          <DetailViewProvider>{children}</DetailViewProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
